//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class dealers_ranking_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.dealers_ranking_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.dealers_ranking_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
protected global::System.Web.UI.WebControls.Repeater rptUsers;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
"BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
"1d50a3a", false, false);
if ((helperClass != null)) {
return helperClass.GetMethod(helperName);
}
return null;
}
private void @__PageInspector_BeginRenderTracing(object[] parameters) {
if ((global::ASP.dealers_ranking_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
global::ASP.dealers_ranking_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
}
}
private void @__PageInspector_EndRenderTracing(object[] parameters) {
if ((global::ASP.dealers_ranking_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
global::ASP.dealers_ranking_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
}
}
public void @__DataBind__control11(object sender, System.EventArgs e) {
System.Web.UI.WebControls.RepeaterItem Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("rank") ;

#line default
#line hidden

#line 2 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("username") ;

#line default
#line hidden

#line 3 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("email") ;

#line default
#line hidden

#line 4 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("total_sales", "{0:N2}") ;

#line default
#line hidden

#line 5 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("rank") ;

#line default
#line hidden

#line 6 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Eval("rank") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
object @__o;

#line 7 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  Session["chat_token"] ;

#line default
#line hidden

#line 8 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  ResolveUrl("~/assets/script/script.js") ;

#line default
#line hidden

#line 9 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  ResolveUrl("~/assets/script/notifications.js") ;

#line default
#line hidden

#line 10 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\11\SE\dealers\ranking.aspx"
@__o =  ResolveUrl("~/assets/script/ranking.js") ;

#line default
#line hidden
}
}
}
