//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_admin_orders_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.TextBox txtSearch;
protected global::System.Web.UI.WebControls.Button btnPending;
protected global::System.Web.UI.WebControls.Button btnApproved;
protected global::System.Web.UI.WebControls.Button btnRejected;
protected global::System.Web.UI.WebControls.GridView gvOrders;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control29(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\16\SE\admin\admin_orders.aspx"
@__o =  GetStatusClass(Eval("status").ToString()) ;

#line default
#line hidden

#line 2 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\16\SE\admin\admin_orders.aspx"
@__o =  Eval("status") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control33(object sender, System.EventArgs e) {
System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 3 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\16\SE\admin\admin_orders.aspx"
@__o =  Eval("order_id") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control36(object sender, System.EventArgs e) {
System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 4 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\16\SE\admin\admin_orders.aspx"
@__o =  Eval("order_id") ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_admin_orders_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.TextBox txtSearch;
protected global::System.Web.UI.WebControls.Button btnPending;
protected global::System.Web.UI.WebControls.Button btnApproved;
protected global::System.Web.UI.WebControls.Button btnRejected;
protected global::System.Web.UI.WebControls.GridView gvOrders;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control29(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\admin_orders.aspx"
@__o =  GetStatusClass(Eval("status").ToString()) ;

#line default
#line hidden

#line 2 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\admin_orders.aspx"
@__o =  Eval("status") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control33(object sender, System.EventArgs e) {
System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 3 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\admin_orders.aspx"
@__o =  Eval("order_id") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control36(object sender, System.EventArgs e) {
System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 4 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\admin_orders.aspx"
@__o =  Eval("order_id") ;

#line default
#line hidden
}
}
}
