//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_dealers_monitoring_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Label lblDate;
protected global::System.Web.UI.WebControls.Label lblTotalDealers;
protected global::System.Web.UI.WebControls.Label lblGrandTotal;
protected global::System.Web.UI.WebControls.Label lblDiamondCount;
protected global::System.Web.UI.WebControls.Label lblPlatinumCount;
protected global::System.Web.UI.WebControls.Label lblGoldCount;
protected global::System.Web.UI.WebControls.Label lblSilverCount;
protected global::System.Web.UI.WebControls.Label lblBronzeCount;
protected global::System.Web.UI.WebControls.GridView gvSales;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control25(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Container.DataItemIndex + 1 ;

#line default
#line hidden
}
public void @__DataBind__control31(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 2 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden

#line 3 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden
}
public void @__DataBind__control36(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 4 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("april_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("april_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control41(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 5 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("may_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("may_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control46(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 6 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("june_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("june_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control51(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 7 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("total_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control76(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 8 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\15\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("next_target")) ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_dealers_monitoring_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Label lblDate;
protected global::System.Web.UI.WebControls.Label lblTotalDealers;
protected global::System.Web.UI.WebControls.Label lblGrandTotal;
protected global::System.Web.UI.WebControls.Label lblDiamondCount;
protected global::System.Web.UI.WebControls.Label lblPlatinumCount;
protected global::System.Web.UI.WebControls.Label lblGoldCount;
protected global::System.Web.UI.WebControls.Label lblSilverCount;
protected global::System.Web.UI.WebControls.Label lblBronzeCount;
protected global::System.Web.UI.WebControls.GridView gvSales;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control23(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Container.DataItemIndex + 1 ;

#line default
#line hidden
}
public void @__DataBind__control29(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 2 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden

#line 3 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden
}
public void @__DataBind__control34(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 4 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("april_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("april_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control39(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 5 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("may_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("may_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control44(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 6 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("june_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("june_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control49(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 7 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("total_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control74(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 8 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("next_target")) ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_dealers_monitoring_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Button btnViewProduct;
protected global::System.Web.UI.WebControls.Label lblDate;
protected global::System.Web.UI.WebControls.Label lblTotalDealers;
protected global::System.Web.UI.WebControls.Label lblGrandTotal;
protected global::System.Web.UI.WebControls.Label lblDiamondCount;
protected global::System.Web.UI.WebControls.Label lblPlatinumCount;
protected global::System.Web.UI.WebControls.Label lblGoldCount;
protected global::System.Web.UI.WebControls.Label lblSilverCount;
protected global::System.Web.UI.WebControls.Label lblBronzeCount;
protected global::System.Web.UI.WebControls.GridView gvSales;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control24(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Container.DataItemIndex + 1 ;

#line default
#line hidden
}
public void @__DataBind__control30(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 2 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden

#line 3 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Eval("computed_rank") ;

#line default
#line hidden
}
public void @__DataBind__control35(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 4 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("april_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("april_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control40(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 5 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("may_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("may_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control45(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 6 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  Convert.ToDecimal(Eval("june_sales")) == 0 ? "–" : String.Format("₱{0:N2}", Eval("june_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control50(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 7 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("total_sales")) ;

#line default
#line hidden
}
public void @__DataBind__control75(object sender, System.EventArgs e) {
System.Web.UI.IDataItemContainer Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));

#line 8 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\dealers_monitoring.aspx"
@__o =  String.Format("₱{0:N2}", Eval("next_target")) ;

#line default
#line hidden
}
}
}
