//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_webpage_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Button btnViewProduct;
protected global::System.Web.UI.WebControls.TextBox txtProductName;
protected global::System.Web.UI.WebControls.TextBox txtPrice;
protected global::System.Web.UI.WebControls.TextBox txtStock;
protected global::System.Web.UI.WebControls.TextBox txtDescription;
protected global::System.Web.UI.WebControls.FileUpload fuProductImage;
protected global::System.Web.UI.WebControls.Button btnSaveProduct;
protected global::System.Web.UI.WebControls.TextBox txtUpdateProductID;
protected global::System.Web.UI.WebControls.TextBox txtUpdateName;
protected global::System.Web.UI.WebControls.TextBox txtUpdatePrice;
protected global::System.Web.UI.WebControls.TextBox txtUpdateStock;
protected global::System.Web.UI.WebControls.TextBox txtUpdateDescription;
protected global::System.Web.UI.WebControls.Button btnSaveUpdate;
protected global::System.Web.UI.WebControls.TextBox txtProductID;
protected global::System.Web.UI.WebControls.Button btnDeleteProduct;
protected global::System.Web.UI.WebControls.Label lblTotalCount;
protected global::System.Web.UI.WebControls.GridView GridView1;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control40(object sender, System.EventArgs e) {
System.Web.UI.WebControls.Image dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Image)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\14\SE\admin\webpage.aspx"
@__o =  ResolveUrl(Eval("image_path").ToString()) ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_webpage_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Button btnViewProduct;
protected global::System.Web.UI.WebControls.TextBox txtProductName;
protected global::System.Web.UI.WebControls.TextBox txtPrice;
protected global::System.Web.UI.WebControls.TextBox txtStock;
protected global::System.Web.UI.WebControls.TextBox txtDescription;
protected global::System.Web.UI.WebControls.FileUpload fuProductImage;
protected global::System.Web.UI.WebControls.Button btnSaveProduct;
protected global::System.Web.UI.WebControls.TextBox txtUpdateProductID;
protected global::System.Web.UI.WebControls.TextBox txtUpdateName;
protected global::System.Web.UI.WebControls.TextBox txtUpdatePrice;
protected global::System.Web.UI.WebControls.TextBox txtUpdateStock;
protected global::System.Web.UI.WebControls.TextBox txtUpdateDescription;
protected global::System.Web.UI.WebControls.Button btnSaveUpdate;
protected global::System.Web.UI.WebControls.TextBox txtProductID;
protected global::System.Web.UI.WebControls.Button btnDeleteProduct;
protected global::System.Web.UI.WebControls.Label lblTotalCount;
protected global::System.Web.UI.WebControls.GridView GridView1;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control40(object sender, System.EventArgs e) {
System.Web.UI.WebControls.Image dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Image)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 1 "C:\Users\Reo Volkov\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\13\SE\admin\webpage.aspx"
@__o =  ResolveUrl(Eval("image_path").ToString()) ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
public class admin_webpage_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Button btnViewProduct;
protected global::System.Web.UI.WebControls.TextBox txtProductName;
protected global::System.Web.UI.WebControls.TextBox txtPrice;
protected global::System.Web.UI.WebControls.TextBox txtStock;
protected global::System.Web.UI.WebControls.TextBox txtDescription;
protected global::System.Web.UI.WebControls.FileUpload fuProductImage;
protected global::System.Web.UI.WebControls.Button btnSaveProduct;
protected global::System.Web.UI.WebControls.TextBox txtUpdateProductID;
protected global::System.Web.UI.WebControls.TextBox txtUpdateName;
protected global::System.Web.UI.WebControls.TextBox txtUpdatePrice;
protected global::System.Web.UI.WebControls.TextBox txtUpdateStock;
protected global::System.Web.UI.WebControls.TextBox txtUpdateDescription;
protected global::System.Web.UI.WebControls.Button btnSaveUpdate;
protected global::System.Web.UI.WebControls.TextBox txtProductID;
protected global::System.Web.UI.WebControls.Button btnDeleteProduct;
protected global::System.Web.UI.WebControls.Label lblTotalCount;
protected global::System.Web.UI.WebControls.GridView GridView1;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control40(object sender, System.EventArgs e) {
System.Web.UI.WebControls.Image dataBindingExpressionBuilderTarget;
System.Web.UI.IDataItemContainer Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Image)(sender));
Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\4C6C1636E48848D82006D7E9B22124358492\12\SE\admin\webpage.aspx"
@__o =  ResolveUrl(Eval("image_path").ToString()) ;

#line default
#line hidden
}
}
}
